export const SPORT_PROFILES={
 soccer:{minProb:.49,minEdge:.018,minEvidence:70,weights:{market:.30,form:.16,h2h:.08,xg:.10,shots:.07,homeAway:.06,availability:.07,rest:.04,movement:.06,calibration:.06}},
 basketball:{minProb:.52,minEdge:.020,minEvidence:72,weights:{market:.30,pace:.14,offRating:.12,defRating:.12,form:.10,backToBack:.08,injuries:.08,movement:.03,calibration:.03}},
 tennis:{minProb:.54,minEdge:.022,minEvidence:74,weights:{market:.34,surface:.14,holdBreak:.14,form:.12,fatigue:.10,serveReturn:.08,movement:.04,calibration:.04}},
 baseball:{minProb:.53,minEdge:.022,minEvidence:74,weights:{market:.30,pitcher:.16,bullpen:.12,wrc:.12,era:.08,park:.06,form:.06,movement:.05,calibration:.05}},
 hockey:{minProb:.53,minEdge:.022,minEvidence:74,weights:{market:.32,xg:.14,goalie:.14,shots:.10,specialTeams:.08,form:.08,movement:.07,calibration:.07}},
 football:{minProb:.53,minEdge:.022,minEvidence:74,weights:{market:.32,epa:.16,pace:.10,injuries:.10,matchup:.10,homeAway:.07,movement:.08,calibration:.07}},
 other:{minProb:.54,minEdge:.025,minEvidence:76,weights:{market:.42,form:.20,movement:.15,calibration:.23}}
};

export const MARKET_ADJUST={
 player_shots:{minEvidence:5,minEdge:.007},player_shots_on_target:{minEvidence:6,minEdge:.008},player_to_receive_card:{minEvidence:7,minEdge:.009},player_goal_scorer_anytime:{minEvidence:8,minEdge:.010},correct_score:{minEvidence:10,minEdge:.014},
 alternate_totals_corners:{minEvidence:4,minEdge:.005},alternate_team_totals_corners:{minEvidence:4,minEdge:.005},alternate_spreads_corners:{minEvidence:4,minEdge:.005},alternate_totals_cards:{minEvidence:4,minEdge:.005},alternate_spreads_cards:{minEvidence:4,minEdge:.005},
 h2h:{minEvidence:0,minEdge:0},totals:{minEvidence:1,minEdge:.002},spreads:{minEvidence:2,minEdge:.003},btts:{minEvidence:2,minEdge:.003}
};

export function family(key=''){key=String(key);if(key.startsWith('soccer_'))return'soccer';if(key.startsWith('basketball_'))return'basketball';if(key.startsWith('tennis_'))return'tennis';if(key.startsWith('baseball_'))return'baseball';if(key.startsWith('icehockey_'))return'hockey';if(key.startsWith('americanfootball_'))return'football';return'other'}
export function policyFor(sport,market){const base=SPORT_PROFILES[family(sport)]||SPORT_PROFILES.other,adj=MARKET_ADJUST[market]||{};return{...base,minEvidence:base.minEvidence+(adj.minEvidence||0),minEdge:base.minEdge+(adj.minEdge||0)}}
export function explanationFor(sport,market,components={}){const p=policyFor(sport,market),w=p.weights||{};return Object.entries(w).map(([factor,weight])=>({factor,weight:Math.round(weight*100),contribution:Number.isFinite(Number(components[factor]))?Number((Number(components[factor])*weight*100).toFixed(2)):null})).sort((a,b)=>b.weight-a.weight)}
export function gatePick(pick,quality){const p=policyFor(pick.sport_key,pick.market),prob=Number(pick.prob),edge=Number(pick.edge),evidence=Number(pick.evidence??pick.evidence_score??0);let state=prob>=p.minProb&&edge>=p.minEdge&&evidence>=p.minEvidence?'APTO':'VIGILAR';const reasons=[];if(prob<p.minProb)reasons.push('probabilidad bajo umbral');if(edge<p.minEdge)reasons.push('edge insuficiente');if(evidence<p.minEvidence)reasons.push('evidencia insuficiente');if(quality?.state==='blocked'){state='NO BET';reasons.push(...(quality.reasons||['calidad de datos bloqueada']))}else if(quality?.state==='watch'&&state==='APTO'){state='VIGILAR';reasons.push('calidad de datos intermedia')}return{state,reasons,policy:p,explanation:explanationFor(pick.sport_key,pick.market,pick.components||{})}}

export function scanAnomalies(events=[]){let quotes=0,badQuotes=0,duplicates=0,incompleteMarkets=0,lineJumps=0,duplicateFixtures=0;const fixtureSet=new Set();for(const e of events){const fk=[String(e.sport_key||''),norm(e.home_team),norm(e.away_team),String(e.commence_time||'').slice(0,16)].join('|');if(fixtureSet.has(fk))duplicateFixtures++;else fixtureSet.add(fk);for(const b of e.bookmakers||[]){const seen=new Set();for(const m of b.markets||[]){if(!Array.isArray(m.outcomes)||m.outcomes.length<2)incompleteMarkets++;const lines=[];for(const o of m.outcomes||[]){quotes++;const price=Number(o.price),k=[m.key,norm(o.name),norm(o.description||''),o.point==null?'':o.point].join('|');if(seen.has(k))duplicates++;seen.add(k);if(!Number.isFinite(price)||price<1.01||price>1000)badQuotes++;if(Number.isFinite(Number(o.point)))lines.push(Number(o.point))}if(lines.length>1&&Math.max(...lines)-Math.min(...lines)>50)lineJumps++}}}const anomalyCount=badQuotes+duplicates+incompleteMarkets+lineJumps+duplicateFixtures;return{quotes,badQuotes,duplicates,incompleteMarkets,lineJumps,duplicateFixtures,anomalyRate:quotes?anomalyCount/quotes:0}}
function norm(v=''){return String(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()}
