const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,Number(v)||0));
export function norm(v=''){return String(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()}
function ou(value,point,name){if(!Number.isFinite(value)||!Number.isFinite(Number(point)))return null;const n=norm(name),p=Number(point);if(Math.abs(value-p)<1e-9)return{voided:true};if(/under|menos/.test(n))return{outcome:value<p?1:0};if(/over|mas/.test(n))return{outcome:value>p?1:0};return null}
function sideFromName(p,event){const n=norm(p.name||p.selection||''),h=norm(p.home_team||event.home_team||''),a=norm(p.away_team||event.away_team||'');if(n.includes(h))return'home';if(n.includes(a))return'away';if(/draw|empate/.test(n))return'draw';return p.side||null}
function teamValue(p,event,home,away){const d=norm(p.description||p.team||''),h=norm(p.home_team||event.home_team||''),a=norm(p.away_team||event.away_team||'');if(d&&d.includes(h))return home;if(d&&d.includes(a))return away;const side=sideFromName(p,event);return side==='home'?home:side==='away'?away:null}
export function settleCore(p,event,detail={}){const final=detail.final||scorePair(event),ht=detail.halftime||null;if(!event||!event.completed||!final)return{...p,settled:false,status:'pending'};const hg=Number(final.home),ag=Number(final.away),m=String(p.market||''),name=String(p.name||p.selection||''),n=norm(name),point=p.point==null?null:Number(p.point),winner=hg>ag?'home':hg<ag?'away':'draw';let r=null;
 if(m==='h2h'){const side=sideFromName(p,event);r=side?{outcome:side===winner?1:0}:null}
 else if(m==='draw_no_bet'){if(winner==='draw')r={voided:true};else{const side=sideFromName(p,event);r=side?{outcome:side===winner?1:0}:null}}
 else if(m==='double_chance'){const x=n.replace(/\s/g,'');r={outcome:(x==='1x'&&winner!=='away')||(x==='x2'&&winner!=='home')||(x==='12'&&winner!=='draw')?1:0}}
 else if(m==='btts'){const yes=hg>0&&ag>0;r={outcome:/yes|si/.test(n)?(yes?1:0):(yes?0:1)}}
 else if(m==='totals'||m==='alternate_totals')r=ou(hg+ag,point,name)
 else if(m==='team_totals'||m==='alternate_team_totals'){const v=teamValue(p,event,hg,ag);r=v==null?null:ou(v,point,name)}
 else if(m==='spreads'||m==='alternate_spreads'){const side=sideFromName(p,event);const margin=side==='home'?hg-ag+Number(point):side==='away'?ag-hg+Number(point):null;r=margin==null?null:Math.abs(margin)<1e-9?{voided:true}:{outcome:margin>0?1:0}}
 else if(m==='h2h_h1'&&ht){const hw=ht.home>ht.away?'home':ht.home<ht.away?'away':'draw',side=sideFromName(p,event);r=side?{outcome:side===hw?1:0}:null}
 else if(m==='totals_h1'&&ht)r=ou(Number(ht.home)+Number(ht.away),point,name)
 else if(m==='alternate_totals_corners')r=ou(Number(detail.corners?.home)+Number(detail.corners?.away),point,name)
 else if(m==='alternate_team_totals_corners'){const v=teamValue(p,event,Number(detail.corners?.home),Number(detail.corners?.away));r=Number.isFinite(v)?ou(v,point,name):null}
 else if(m==='alternate_spreads_corners'){const side=sideFromName(p,event),h=Number(detail.corners?.home),a=Number(detail.corners?.away),margin=side==='home'?h-a+Number(point):side==='away'?a-h+Number(point):null;r=Number.isFinite(margin)?Math.abs(margin)<1e-9?{voided:true}:{outcome:margin>0?1:0}:null}
 else if(m==='corners_1x2'){const h=Number(detail.corners?.home),a=Number(detail.corners?.away),cw=h>a?'home':h<a?'away':'draw',side=sideFromName(p,event);r=Number.isFinite(h)&&Number.isFinite(a)&&side?{outcome:side===cw?1:0}:null}
 else if(m==='alternate_totals_cards')r=ou(Number(detail.cards?.home)+Number(detail.cards?.away),point,name)
 else if(m==='alternate_spreads_cards'){const side=sideFromName(p,event),h=Number(detail.cards?.home),a=Number(detail.cards?.away),margin=side==='home'?h-a+Number(point):side==='away'?a-h+Number(point):null;r=Number.isFinite(margin)?Math.abs(margin)<1e-9?{voided:true}:{outcome:margin>0?1:0}:null}
 else if(/^player_/.test(m)){const ps=findPlayer(detail.players||[],p);if(ps){if(m==='player_shots')r=ou(Number(ps.shots),point,name);else if(m==='player_shots_on_target'||m==='player_shots_on_goal')r=ou(Number(ps.shots_on_target),point,name);else if(m==='player_goals'||m==='player_goal_scorer_anytime')r=/yes|over|score|marca|anot/.test(n)?{outcome:Number(ps.goals)>0?1:0}:ou(Number(ps.goals),point,name);else if(m==='player_to_receive_card')r={outcome:(Number(ps.yellow)+Number(ps.red))>0?1:0}}}
 if(!r)return finalize(p,{status:'unsupported_data'});return finalize(p,r,{final_score:`${hg}-${ag}`})}
function finalize(p,r,extra={}){if(r&&r.status==='unsupported_data')return{...p,settled:false,status:'unsupported_data'};const voided=!!r.voided,outcome=voided?null:Number(r.outcome),price=Number(p.price),prob=clamp(p.prob),close=Number(p.close_price||p.closing_price),roi=voided?0:(outcome===1&&price>1?price-1:-1),brier=voided?null:Math.pow(prob-(outcome||0),2),clv=Number.isFinite(close)&&close>1&&price>1?((price/close)-1)*100:null;return{...p,...extra,settled:true,voided,outcome,status:voided?'void':outcome===1?'won':'lost',roi,brier,closing_price:Number.isFinite(close)?close:null,clv_pp:Number.isFinite(clv)?clv:null,settled_at:new Date().toISOString()}}
function findPlayer(players,p){const want=norm(p.player||p.description||p.name||p.selection||'');return players.find(x=>{const n=norm(x.name||x.player||'');return n&&want&&(want.includes(n)||n.includes(want))})||null}
export function scorePair(event){const scores=Array.isArray(event?.scores)?event.scores:[];if(scores.length<2)return null;const home=scores.find(x=>norm(x.name)===norm(event.home_team))||scores[0],away=scores.find(x=>norm(x.name)===norm(event.away_team))||scores[1],h=Number(home?.score),a=Number(away?.score);return Number.isFinite(h)&&Number.isFinite(a)?{home:h,away:a}:null}
