(function(){
'use strict';
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(f))}catch{return f}};
const write=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}};
const api=async(path,opt={})=>{const r=await fetch(path,{method:opt.method||'GET',headers:{'content-type':'application/json'},body:opt.body?JSON.stringify(opt.body):undefined});const t=await r.text();let d;try{d=t?JSON.parse(t):{}}catch{d={error:t}}if(!r.ok)throw new Error(d.error||d.message||`HTTP ${r.status}`);return d};
function quality(){return read('mq_quality_gate_v1',{state:'blocked',score:0,reasons:['quality gate no inicializado']})}
function enforceDom(){const q=quality();if(q.state==='active')return;document.querySelectorAll('body *').forEach(el=>{if(el.children.length) return;const t=(el.textContent||'').trim();if(t==='APTO'){el.textContent=q.state==='blocked'?'NO BET':'VIGILAR';el.dataset.qualityGate='1';el.title='Estado degradado por quality gate: '+(q.reasons||[]).join(', ')}})}
async function verifyProduction(){try{const d=await api('/api/preflight');write('mq_preflight_status',{ok:true,...d,at:Date.now()});return true}catch(e){write('mq_preflight_status',{ok:false,error:e.message,at:Date.now()});return false}finally{renderBanner()}}
function sameOutcome(o,p){const n=v=>String(v==null?'':v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();return n(o.name)===n(p.name||p.selection||'')&&n(o.description||'')===n(p.description||'')&&((o.point==null&&p.point==null)||Number(o.point)===Number(p.point))}
async function captureClosingLines(){const h=read('mq_history',[]),now=Date.now();let changed=false;for(const p of h){if(!p||p.settled||p.closing_price||!p.event_id||!p.sport_key||!p.market)continue;const ko=new Date(p.kickoff||0).getTime();if(!ko||ko<now-5*60000||ko>now+45*60000)continue;try{const d=await api('/api/closing-line',{method:'POST',body:{pick:p,region:p.region||'eu'}});if(d.closing&&Number(d.closing.price)>1){p.closing_price=Number(d.closing.price);p.closing_bookmaker=d.closing.bookmaker;p.closing_captured_at=d.captured_at;changed=true}}catch{}}
 if(changed){write('mq_history',h);try{await api('/api/state?scope=prod',{method:'POST',body:{state:{history:h.slice(-800)}}})}catch{}}
}
async function pullDurable(){try{const d=await api('/api/state?scope=prod');write('mq_persistence_status',{...d.persistence,ok:true,at:Date.now()});if(!d.persistence?.durable)throw new Error('Persistencia durable no configurada');const remote=d.state||{},local=read('mq_history',[]);if(Array.isArray(remote.history)&&remote.history.length>=local.length)write('mq_history',remote.history);return true}catch(e){write('mq_persistence_status',{ok:false,durable:false,error:e.message,at:Date.now()});return false}finally{renderBanner()}}
function mountBanner(){if(document.getElementById('prodIntegrationBanner'))return;const b=document.createElement('div');b.id='prodIntegrationBanner';b.style.cssText='position:fixed;left:12px;bottom:12px;z-index:9999;padding:8px 10px;border-radius:8px;background:#071820;border:1px solid rgba(90,220,240,.22);color:#dffaff;font:600 11px Inter,sans-serif;max-width:360px;box-shadow:0 8px 30px rgba(0,0,0,.35);transition:opacity .2s ease,transform .2s ease';document.body.appendChild(b);renderBanner()}
function renderBanner(){const b=document.getElementById('prodIntegrationBanner');if(!b)return;const p=read('mq_preflight_status',{}),s=read('mq_persistence_status',{}),q=quality();const infraOk=!!(p.ok&&s.durable);if(infraOk){b.textContent=q.state==='blocked'?'PRODUCCIÓN OK · quality gate esperando datos':'PRODUCCIÓN OK · Persistencia activa';b.style.color='#78ff96';b.style.opacity='0';b.style.transform='translateY(6px)';b.style.pointerEvents='none';setTimeout(()=>{if(document.getElementById('prodIntegrationBanner')===b&&read('mq_preflight_status',{}).ok&&read('mq_persistence_status',{}).durable)b.style.display='none'},250);return}b.style.display='block';b.style.opacity='1';b.style.transform='none';b.style.pointerEvents='auto';b.textContent='PRODUCCIÓN DEGRADADA · '+[p.ok?'':'preflight',s.durable?'':'persistencia'].filter(Boolean).join(' · ');b.style.color='#ffd166'}
async function refreshStatus(){await Promise.allSettled([verifyProduction(),pullDurable()]);renderBanner();enforceDom()}
function boot(){mountBanner();refreshStatus();captureClosingLines();enforceDom();const mo=new MutationObserver(()=>{enforceDom();renderBanner()});mo.observe(document.documentElement,{childList:true,subtree:true,characterData:true});setInterval(()=>{refreshStatus();captureClosingLines()},30000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
