import './styles.css';

const $=s=>document.querySelector(s);
const state={sports:[],events:[],tab:'events',marketIntel:JSON.parse(localStorage.getItem('mq_market_intel')||'{}'),history:JSON.parse(localStorage.getItem('mq_history')||'[]'),calibration:{market_bins:{},walk_forward:{samples:0,by_market:{}}}};

async function api(path,method='GET',body){const r=await fetch('/api/'+path,{method,headers:{'content-type':'application/json'},body:body?JSON.stringify(body):undefined});const d=await r.json().catch(()=>({error:'Respuesta inválida'}));if(!r.ok)throw new Error(d.error||'Error '+r.status);return d}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function norm(v){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()}
function sk(o){return [o.market,o.description||'',o.name,o.point==null?'':o.point].join('|')}
function marketName(k){return({h2h:'Ganador / Moneyline',totals:'Totales',spreads:'Hándicap',btts:'Ambos marcan',double_chance:'Doble oportunidad',draw_no_bet:'Empate no acción',team_totals:'Total por equipo',alternate_totals:'Totales alternativos',alternate_team_totals:'Total equipo alternativo',alternate_totals_corners:'Córners totales',alternate_team_totals_corners:'Córners por equipo',alternate_totals_cards:'Tarjetas totales'})[k]||String(k||'Mercado').replaceAll('_',' ')}
function choice(o){return (o.description?o.description+' — ':'')+o.name+(o.point==null?'':' '+(Number(o.point)>0?'+':'')+o.point)}
function best(e){const m={};for(const b of e.bookmakers||[])for(const mk of b.markets||[])for(const o of mk.outcomes||[]){const id=[mk.key,o.description||'',o.name,o.point==null?'':o.point].join('|');if(!m[id])m[id]={market:mk.key,name:o.name,description:o.description||'',point:o.point,price:Number(o.price),book:b.title,quotes:[]};m[id].quotes.push({book:b.title,price:Number(o.price)});if(Number(o.price)>m[id].price){m[id].price=Number(o.price);m[id].book=b.title}}return Object.values(m).map(o=>{o.quotes.sort((a,b)=>b.price-a.price);o.bookCount=o.quotes.length;o.avgPrice=o.quotes.reduce((a,x)=>a+x.price,0)/Math.max(1,o.quotes.length);return o}).sort((a,b)=>b.price-a.price)}
function consensus(e){const g={};for(const b of e.bookmakers||[])for(const m of b.markets||[]){const groups={};for(const o of m.outcomes||[]){const id=[m.key,o.description||'',o.point==null?'':o.point].join('|');(groups[id]??=[]).push(o)}for(const id in groups){const arr=groups[id],z=arr.reduce((a,o)=>a+1/Number(o.price),0);if(arr.length<2||!z)continue;for(const o of arr){const key=[m.key,o.description||'',o.name,o.point==null?'':o.point].join('|');(g[key]??=[]).push((1/Number(o.price))/z)}}}const out={};for(const k in g)out[k]=g[k].reduce((a,b)=>a+b,0)/g[k].length;return out}
function quoteReliability(o){const q=o.quotes||[],avg=q.length?q.reduce((a,x)=>a+x.price,0)/q.length:o.price,v=q.length?q.reduce((a,x)=>a+(x.price-avg)**2,0)/q.length:0,disp=avg?Math.sqrt(v)/avg:.2;let r=.42+Math.min(.34,q.length/6*.34)+Math.max(0,1-Math.min(.2,disp)/.2)*.18;if(q.length<2)r=Math.min(r,.52);return{r:Math.max(.35,Math.min(.94,r)),disp}}
function historyAdjust(p,m){const bins=state.calibration.market_bins?.[m]||[],b=bins.find(x=>x.active&&Number(x.samples)>=12&&p>=x.lo&&p<x.hi);if(!b)return{p,adj:0,n:0};const wf=state.calibration.walk_forward?.by_market?.[m],wfN=Number(wf?.samples||0),wfGap=wf&&wf.estimated_hit_rate!=null&&wf.hit_rate!=null?Number(wf.hit_rate)-Number(wf.estimated_hit_rate):0,dir=Math.sign(Number(b.adjustment)||0),wfDir=Math.sign(wfGap||0);let gate=wfN>=12&&dir&&wfDir&&dir!==wfDir?.25:1;const adj=Math.max(-.04,Math.min(.04,Number(b.adjustment)||0))*gate;return{p:Math.max(.02,Math.min(.98,p+adj)),adj,n:Number(b.samples||0)}}
function modelProb(e,o){const p=e.football_prediction;if(!p||!p.percent)return null;const n=norm(o.name),h=Number(String(p.percent.home||'').replace('%','')),d=Number(String(p.percent.draw||'').replace('%','')),a=Number(String(p.percent.away||'').replace('%',''));if(o.market==='h2h'){if(n===norm(e.home_team))return h/100;if(n===norm(e.away_team))return a/100;if(/draw|empate/.test(n))return d/100}if(o.market==='double_chance'){if(n==='1x')return(h+d)/100;if(n==='x2')return(a+d)/100;if(n==='12')return(h+a)/100}return null}
function contextFactor(e,o){const a=e.football_prediction?.availability;if(!a?.checked)return 1;const side=norm(o.name)===norm(e.home_team)?'home':norm(o.name)===norm(e.away_team)?'away':null;const hi=Number(a.impact?.home||0),ai=Number(a.impact?.away||0),hf=Number(a.fatigue?.home||0),af=Number(a.fatigue?.away||0);let pen=a.injury_coverage===false?.025:0;if(side==='home')pen+=Math.max(0,hi-ai)*.22+hi*.04+hf*.05;else if(side==='away')pen+=Math.max(0,ai-hi)*.22+ai*.04+af*.05;else pen+=Math.max(hi,ai)*.06+Math.max(hf,af)*.025;return 1-Math.min(.22,Math.max(0,pen))}
function cand(e){const c=consensus(e);return best(e).map(o=>{const base=c[sk(o)]||1/o.price;let p=base,mp=modelProb(e,o);if(mp!=null)p=p*.65+mp*.35;const q=quoteReliability(o);q.r=Math.max(.35,Math.min(.94,q.r*contextFactor(e,o)));p=base+(p-base)*q.r;const h=historyAdjust(p,o.market);p=h.p;const edge=p*o.price-1,evidence=Math.round(Math.max(0,Math.min(100,q.r*80+Math.min(h.n/30,1)*15+Math.min(o.bookCount,6)/6*5))),decision=edge<=0||q.r<.52?'NO BET':p>=.48&&edge>=.015&&evidence>=68?'APTO':'VIGILAR';return{...o,prob:p,marketProb:base,reliability:q.r,uncertainty:1-q.r,historyAdjustment:h.adj,historySamples:h.n,edge,evidence,decision,rank:p*.72+q.r*.2+Math.max(0,Math.min(edge,.12))*.4}}).sort((a,b)=>b.rank-a.rank)}
function category(m){if(['h2h','double_chance','draw_no_bet'].includes(m))return'Resultado';if(/corner/.test(m))return'Córners';if(/card/.test(m))return'Tarjetas';if(/spread/.test(m))return'Hándicap';if(/total|btts/.test(m))return'Goles / Puntos';return'Otros'}
function availabilityHtml(e){const a=e.football_prediction?.availability;if(!a?.checked)return'';const hi=a.injuries?.home||{count:0,players:[]},ai=a.injuries?.away||{count:0,players:[]},r=a.rest||{};return`<section class="context"><header><b>Disponibilidad y contexto</b><span class="${a.injury_coverage?'ok':'warn'}">${a.injury_coverage?'Bajas verificadas':'Lesiones sin cobertura'}</span></header><div><article><strong>${esc(e.home_team)}</strong><small>${hi.count} bajas · impacto ${Math.round(Number(a.impact?.home||0)*100)}%</small><small>Descanso ${r.home_days==null?'—':Number(r.home_days).toFixed(1)+' d'} · ${r.home_matches_7d||0} PJ/7d</small></article><article><strong>${esc(e.away_team)}</strong><small>${ai.count} bajas · impacto ${Math.round(Number(a.impact?.away||0)*100)}%</small><small>Descanso ${r.away_days==null?'—':Number(r.away_days).toFixed(1)+' d'} · ${r.away_matches_7d||0} PJ/7d</small></article></div></section>`}
function eventCard(e){const rows=cand(e),groups={};for(const o of rows)(groups[category(o.market)]??=[]).push(o);return`<article class="event"><header><span>${esc(e.sport_title)}</span><h3>${esc(e.home_team)} vs ${esc(e.away_team)}</h3><time>${new Date(e.commence_time).toLocaleString('es-CO',{dateStyle:'short',timeStyle:'short'})}</time></header>${availabilityHtml(e)}<div class="markets">${Object.entries(groups).filter(([,r])=>r.length).map(([g,r])=>`<section><div class="market-head"><b>${g}</b><small>${r.length} opciones</small></div><div class="quotes">${r.slice(0,6).map(o=>`<div class="quote"><div><strong>${esc(choice(o))}</strong><small>${esc(o.book)} · ${o.bookCount} casa${o.bookCount===1?'':'s'}</small><span class="decision ${o.decision.toLowerCase().replace(' ','-')}">${o.decision}</span><span class="meta">Prob. ${(o.prob*100).toFixed(1)}% · EV ${(o.edge*100).toFixed(1)}% · Fiab. ${(o.reliability*100).toFixed(0)}% · Evid. ${o.evidence}/100</span></div><b>${o.price.toFixed(2)}</b></div>`).join('')}</div></section>`).join('')}</div></article>`}
function performance(){const w=state.calibration.walk_forward||{},by=w.by_market||{};return`<section class="perf"><div class="hero"><div><small>MODEL PERFORMANCE DESK</small><h2>RENDIMIENTO DEL MOTOR</h2><p>Walk-forward cronológico · mínimo 12 observaciones por tramo antes de recalibrar.</p></div></div><div class="kpis"><div><small>Muestra</small><b>${w.samples||0}</b></div><div><small>Brier</small><b>${w.brier==null?'—':Number(w.brier).toFixed(3)}</b></div><div><small>Acierto real</small><b>${w.hit_rate==null?'—':(w.hit_rate*100).toFixed(1)+'%'}</b></div><div><small>Acierto est.</small><b>${w.estimated_hit_rate==null?'—':(w.estimated_hit_rate*100).toFixed(1)+'%'}</b></div><div><small>ROI</small><b>${w.roi==null?'—':(w.roi*100).toFixed(1)+'%'}</b></div></div><table><thead><tr><th>Mercado</th><th>n</th><th>Acierto</th><th>Brier</th><th>ROI</th></tr></thead><tbody>${Object.entries(by).sort((a,b)=>Number(b[1].samples)-Number(a[1].samples)).map(([m,x])=>`<tr><td>${esc(marketName(m))}</td><td>${x.samples||0}</td><td>${x.hit_rate==null?'—':(x.hit_rate*100).toFixed(1)+'%'}</td><td>${x.brier==null?'—':Number(x.brier).toFixed(3)}</td><td>${x.roi==null?'—':(x.roi*100).toFixed(1)+'%'}</td></tr>`).join('')}</tbody></table></section>`}
function render(){const content=$('#content');if(state.tab==='performance'){content.innerHTML=performance();return}content.innerHTML=state.events.length?state.events.map(eventCard).join(''):`<div class="empty"><b>LIVE ODDS CONSOLE</b><p>Selecciona competiciones y pulsa Consultar fecha.</p></div>`;metrics()}
function metrics(){const picks=state.events.flatMap(cand),apto=picks.filter(x=>x.decision==='APTO');$('#mEvents').textContent=state.events.length;$('#mMarkets').textContent=new Set(state.events.flatMap(e=>(e.bookmakers||[]).flatMap(b=>(b.markets||[]).map(m=>m.key)))).size;$('#mBooks').textContent=new Set(state.events.flatMap(e=>(e.bookmakers||[]).map(b=>b.key))).size;$('#mEdges').textContent=apto.length;$('#mHit').textContent=apto.length?(apto.slice(0,6).reduce((a,x)=>a+x.prob,0)/Math.min(6,apto.length)*100).toFixed(1)+'%':'—'}
function appShell(){document.body.innerHTML=`<div class="app"><header class="top"><div class="logo">MQ</div><div><b>MONEY QUANT BETTOR</b><small>DATOS · MODELOS · APUESTAS INTELIGENTES</small></div><button id="sync">Consultar fecha</button></header><div class="grid"><aside><label>Desde<input id="from" type="date"></label><label>Hasta<input id="to" type="date"></label><label>Región<select id="region"><option value="eu">Europa</option><option value="uk">UK</option><option value="us">USA</option><option value="au">Australia</option></select></label><label>Competiciones<div id="sports" class="sports">Cargando…</div></label></aside><main><section class="hero"><small>SPORTS INTELLIGENCE</small><h1>INTELIGENCIA DE CUOTAS DEPORTIVAS</h1><p>Cuotas multi-casa, contexto prepartido y recalibración por mercado con validación walk-forward.</p></section><section class="metrics"><div><small>Eventos</small><b id="mEvents">0</b></div><div><small>Mercados</small><b id="mMarkets">0</b></div><div><small>Casas</small><b id="mBooks">0</b></div><div><small>Picks APTO</small><b id="mEdges">0</b></div><div><small>Acierto motor</small><b id="mHit">—</b></div></section><div class="status"><span id="status">Listo</span><span id="quota">Créditos —</span></div><nav><button data-tab="events" class="on">Partidos y cuotas</button><button data-tab="performance">Rendimiento</button></nav><section id="content"></section></main></div></div>`;const d=new Date(),t=new Date(Date.now()+86400000);$('#from').value=d.toISOString().slice(0,10);$('#to').value=t.toISOString().slice(0,10);document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.remove('on'));b.classList.add('on');state.tab=b.dataset.tab;render()});$('#sync').onclick=sync}
async function loadSports(){try{state.sports=(await api('sports')).filter(s=>s.active&&!s.has_outrights);const saved=new Set(JSON.parse(localStorage.getItem('mq_sports')||'[]'));$('#sports').innerHTML=state.sports.map((s,i)=>`<label><input type="checkbox" value="${esc(s.key)}" ${(saved.has(s.key)||(!saved.size&&i<14))?'checked':''}>${esc(s.title)}</label>`).join('');$('#sports').onchange=()=>localStorage.setItem('mq_sports',JSON.stringify([...document.querySelectorAll('#sports input:checked')].map(x=>x.value)))}catch(e){$('#sports').textContent=e.message}}
async function refreshContext(){const football=state.events.filter(e=>/^soccer_/.test(e.sport_key)).slice(0,8).map(e=>({id:e.id,home:e.home_team,away:e.away_team,time:e.commence_time}));if(!football.length)return;try{const d=await api('football-insights','POST',{events:football});for(const x of d.insights||[]){const e=state.events.find(v=>v.id===x.id);if(e){e.football_prediction=x.prediction;e.football_fixture_id=x.fixture}}}catch{}
}
async function refreshIntel(){const snaps=[];for(const e of state.events)for(const o of best(e).filter(x=>['h2h','totals','team_totals','alternate_totals'].includes(x.market)).slice(0,6)){const c=consensus(e),p=c[sk(o)]||1/o.price;snaps.push({event_id:String(e.id),sport_key:e.sport_key,kickoff:e.commence_time,selection:sk(o),market:o.market,name:o.name,description:o.description,point:o.point,price:o.price,consensus_prob:p,books:o.bookCount})}if(!snaps.length)return;try{const d=await api('market-intel','POST',{snapshots:snaps,previous:state.marketIntel});state.marketIntel=d.intel||{};localStorage.setItem('mq_market_intel',JSON.stringify(state.marketIntel))}catch{}}
async function recalibrate(){const preds=[];for(const e of state.events){if(!e.football_fixture_id)continue;for(const o of cand(e).filter(x=>['h2h','double_chance','draw_no_bet','totals','alternate_totals','team_totals','alternate_team_totals','btts'].includes(x.market)).slice(0,8))preds.push({fixture:Number(e.football_fixture_id),side:o.market==='h2h'?(norm(o.name)===norm(e.home_team)?'home':norm(o.name)===norm(e.away_team)?'away':/draw|empate/i.test(o.name)?'draw':undefined):undefined,market:o.market,name:o.name,description:o.description||'',point:o.point,price:o.price,prob:o.prob,market_prob:o.marketProb,kickoff:e.commence_time,home_team:e.home_team,away_team:e.away_team})}if(!preds.length)return;try{const d=await api('model-history','POST',{history:state.history,predictions:preds});state.history=d.history||state.history;state.calibration=d.calibration||state.calibration;localStorage.setItem('mq_history',JSON.stringify(state.history))}catch{}}
async function sync(){const sports=[...document.querySelectorAll('#sports input:checked')].map(x=>x.value);if(!sports.length)return;$('#sync').disabled=true;$('#status').textContent='Consultando cuotas…';try{const d=await api('odds','POST',{sports,markets:['h2h','totals','spreads'],region:$('#region').value,from:$('#from').value,to:$('#to').value});state.events=d.events||[];$('#quota').textContent='Créditos '+(d.quota?.remaining??'—')+' · costo '+(d.quota?.last??0);$('#status').textContent='Procesando contexto y recalibración…';await refreshContext();await refreshIntel();await recalibrate();$('#status').textContent='Motor actualizado · procesamiento directo Vercel';render()}catch(e){$('#status').textContent=e.message}finally{$('#sync').disabled=false}}

appShell();loadSports();render();
