(function(){
'use strict';
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(f))}catch{return f}};
const write=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}};
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,Number(v)||0));
const esc=s=>String(s==null?'':s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const API_BASE=location.hostname.endsWith('github.io')?'https://money-quant-bettor-duque3.vercel.app':'';
const scope='prod';

const SPORT_PROFILES={
 soccer:{minProb:.49,minEdge:.018,minEvidence:70,weights:{market:.32,form:.20,h2h:.10,availability:.10,rest:.06,movement:.12,calibration:.10}},
 basketball:{minProb:.52,minEdge:.020,minEvidence:72,weights:{market:.38,pace:.18,form:.16,injuries:.10,movement:.10,calibration:.08}},
 tennis:{minProb:.54,minEdge:.022,minEvidence:74,weights:{market:.40,surface:.16,form:.18,serveReturn:.12,movement:.08,calibration:.06}},
 baseball:{minProb:.53,minEdge:.022,minEvidence:74,weights:{market:.34,pitching:.22,batting:.16,park:.08,movement:.12,calibration:.08}},
 hockey:{minProb:.53,minEdge:.022,minEvidence:74,weights:{market:.36,goalie:.18,form:.15,specialTeams:.10,movement:.12,calibration:.09}},
 football:{minProb:.53,minEdge:.022,minEvidence:74,weights:{market:.36,epa:.18,injuries:.13,matchup:.12,movement:.12,calibration:.09}},
 other:{minProb:.54,minEdge:.025,minEvidence:76,weights:{market:.45,form:.20,movement:.15,calibration:.20}}
};
const MARKET_ADJUST={player_shots:{minEvidence:+4,minEdge:+.006},player_shots_on_target:{minEvidence:+5,minEdge:+.007},correct_score:{minEvidence:+8,minEdge:+.012},alternate_totals_corners:{minEvidence:+3,minEdge:+.004},alternate_totals_cards:{minEvidence:+3,minEdge:+.004},h2h:{minEvidence:0,minEdge:0},totals:{minEvidence:+1,minEdge:+.002},spreads:{minEvidence:+2,minEdge:+.003}};

function family(k=''){if(k.startsWith('soccer_'))return'soccer';if(k.startsWith('basketball_'))return'basketball';if(k.startsWith('tennis_'))return'tennis';if(k.startsWith('baseball_'))return'baseball';if(k.startsWith('icehockey_'))return'hockey';if(k.startsWith('americanfootball_'))return'football';return'other'}
function policyFor(sport,market){const base=SPORT_PROFILES[family(sport)]||SPORT_PROFILES.other,adj=MARKET_ADJUST[market]||{};return{...base,minEvidence:base.minEvidence+(adj.minEvidence||0),minEdge:base.minEdge+(adj.minEdge||0)}}
write('mq_model_policy_v1',{version:'sport-market-v1',profiles:SPORT_PROFILES,marketAdjust:MARKET_ADJUST,updatedAt:Date.now()});

function snapshot(){return read('mq_odds_snapshot_v2',{})||{}}
function dataQuality(){const s=snapshot(),events=Array.isArray(s.events)?s.events:[],age=s.at?Date.now()-Number(s.at):Infinity;let books=0,withBooks=0,quotes=0,badQuotes=0,dup=0,incomplete=0,football=0,context=0;events.forEach(e=>{const bs=Array.isArray(e.bookmakers)?e.bookmakers:[];if(bs.length){withBooks++;books+=bs.length}if(family(String(e.sport_key||''))==='soccer'){football++;if(e.football_prediction)context++}bs.forEach(b=>{const seen=new Set();(b.markets||[]).forEach(m=>{if(!m.outcomes||m.outcomes.length<2)incomplete++;(m.outcomes||[]).forEach(o=>{quotes++;const p=Number(o.price),key=[m.key,o.name,o.description||'',o.point==null?'':o.point].join('|');if(seen.has(key))dup++;else seen.add(key);if(!Number.isFinite(p)||p<1.01||p>1000)badQuotes++})})})});const freshness=age<=20*60000?1:age<=60*60000?.8:age<=2*3600000?.5:age<=6*3600000?.2:0,avgBooks=events.length?books/events.length:0,coverage=events.length?withBooks/events.length:0,ctx=football?context/football:1,anomalyRate=quotes?(badQuotes+dup+incomplete)/quotes:0,hist=read('mq_history',[]).filter(x=>x&&x.settled).length;const score=Math.round(100*(freshness*.28+clamp(avgBooks/5)*.23+coverage*.14+ctx*.15+clamp(hist/100)*.12+(1-clamp(anomalyRate/.08))*.08));const state=score<45||freshness<.25||coverage<.45?'blocked':score<70||anomalyRate>.04?'watch':'active';const reasons=[];if(freshness<.5)reasons.push('cuotas antiguas');if(avgBooks<2)reasons.push('pocas casas');if(coverage<.65)reasons.push('cobertura baja');if(ctx<.55)reasons.push('contexto deportivo incompleto');if(anomalyRate>.04)reasons.push('anomalías de cuotas');if(hist<20)reasons.push('muestra histórica pequeña');const gate={score,state,reasons,updatedAt:Date.now(),metrics:{age,avgBooks,coverage,context:ctx,anomalyRate,quotes,badQuotes,duplicates:dup,incompleteMarkets:incomplete,history:hist}};write('mq_quality_gate_v1',gate);write('mq_anomaly_report_v1',{at:Date.now(),badQuotes,duplicates:dup,incompleteMarkets:incomplete,anomalyRate,events:events.length});return gate}

async function api(path,opt={}){const r=await fetch(API_BASE+path,{method:opt.method||'GET',headers:{'content-type':'application/json'},body:opt.body?JSON.stringify(opt.body):undefined});const t=await r.text();let d={};try{d=t?JSON.parse(t):{}}catch{d={error:t}}if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);return d}
function safeState(){return{history:read('mq_history',[]).slice(-1500),marketIntel:read('mq_market_intel',{}),alerts:read('mq_engine_alerts',[]).slice(-100),chartFilters:read('mq_chart_filters_v1',{}),quality:dataQuality(),updatedAt:Date.now()}}
async function pullState(){try{const d=await api('/api/state?scope='+scope),s=d.state||{};const local=read('mq_history',[]),remote=Array.isArray(s.history)?s.history:[];if(remote.length>local.length)write('mq_history',remote);if(s.marketIntel&&Object.keys(s.marketIntel).length>Object.keys(read('mq_market_intel',{})).length)write('mq_market_intel',s.marketIntel);write('mq_persistence_status',{...d.persistence,ok:true,at:Date.now()})}catch(e){write('mq_persistence_status',{ok:false,error:e.message,at:Date.now()})}}
async function pushState(){try{const d=await api('/api/state?scope='+scope,{method:'POST',body:{replace:true,state:safeState()}});write('mq_persistence_status',{...d.persistence,ok:true,at:Date.now()})}catch(e){write('mq_persistence_status',{ok:false,error:e.message,at:Date.now()})}}
async function autoSettle(){const history=read('mq_history',[]),pending=history.filter(x=>x&&x.sport_key&&!x.settled&&new Date(x.kickoff||0).getTime()<Date.now()-90*60000);if(!pending.length)return;try{const d=await api('/api/settle',{method:'POST',body:{scope,picks:history}});if(Array.isArray(d.history)){write('mq_history',d.history);diagnoseErrors(d.history);window.dispatchEvent(new StorageEvent('storage',{key:'mq_history'}))}}catch(e){write('mq_settlement_status',{ok:false,error:e.message,at:Date.now()})}}

function diagnoseErrors(history){const lost=(history||[]).filter(r=>r&&r.settled&&!r.voided&&Number(r.outcome)===0).slice(-30).reverse(),rows=lost.map(r=>{const p=Number(r.prob||0),edge=Number(r.edge||0),market=String(r.market||''),sport=String(r.sport_key||''),pol=policyFor(sport,market);let cause='Resultado adverso dentro de la varianza esperada',adjustment='Mantener calibración';if(p>=.68)cause='Sobreconfianza del modelo';else if(edge>=.08)cause='Edge estimado probablemente inflado';else if(/player_/.test(market))cause='Prop de jugador con alta sensibilidad a minutos/rol';else if(/total|btts/.test(market))cause='Ritmo/goles reales desviados del escenario central';if(p>=.68)adjustment='Reducir confianza 1–3 pp hasta recuperar calibración';else if(edge>=.08)adjustment='Aplicar shrinkage adicional al edge';else if(/player_/.test(market))adjustment='Exigir mayor evidencia y alineación/rol confirmado';else adjustment=`Revisar perfil ${family(sport)} / ${market||'mercado'}`;return{at:r.settled_at||r.kickoff,market,sport,selection:r.name||r.selection||'Pick',prob:p,edge,cause,adjustment,policy:{minProb:pol.minProb,minEdge:pol.minEdge,minEvidence:pol.minEvidence}}});write('mq_model_errors_v1',rows)}

function explanationWeights(row){const p=policyFor(String(row&&row.sport_key||''),String(row&&row.market||'')),w=p.weights||{};return Object.entries(w).sort((a,b)=>b[1]-a[1]).map(([k,v])=>({factor:k,weight:Math.round(v*100)}))}
function enrichHistory(){const h=read('mq_history',[]);let changed=false;h.forEach(r=>{if(!r||r.explanation_weights)return;r.explanation_weights=explanationWeights(r);r.model_profile=family(String(r.sport_key||''));changed=true});if(changed)write('mq_history',h)}

function mountOpsPanel(){if(document.getElementById('mqOpsPanel'))return;const anchor=document.getElementById('modelAnalyticsPanel')||document.getElementById('backtestStrip');if(!anchor)return;const el=document.createElement('section');el.id='mqOpsPanel';el.style.cssText='margin:7px;padding:10px;border:1px solid rgba(90,180,200,.16);border-radius:9px;background:rgba(3,16,22,.9);color:#dffaff;font:12px Inter,sans-serif';el.innerHTML='<div style="display:flex;justify-content:space-between;gap:12px;align-items:center"><div><b>MODEL OPS · PRODUCCIÓN</b><div style="opacity:.6;font-size:10px">Persistencia · liquidación · anomalías · perfiles por deporte</div></div><span id="mqOpsState" style="font-weight:700">—</span></div><div id="mqOpsGrid" style="display:grid;grid-template-columns:repeat(4,1fr);gap:6px;margin-top:8px"></div><div style="margin-top:10px"><b style="font-size:11px">ERRORES RECIENTES Y AUTOCORRECCIÓN</b><div id="mqErrorRows" style="display:grid;gap:5px;margin-top:6px"></div></div>';anchor.insertAdjacentElement('afterend',el);renderOps()}
function renderOps(){const el=document.getElementById('mqOpsPanel');if(!el)return;const g=read('mq_quality_gate_v1',{}),p=read('mq_persistence_status',{}),a=read('mq_anomaly_report_v1',{}),h=read('mq_history',[]),settled=h.filter(x=>x&&x.settled).length,pending=h.filter(x=>x&&!x.settled&&x.sport_key).length;document.getElementById('mqOpsState').textContent=(g.state||'—').toUpperCase()+' · '+(g.score??'—')+'/100';const cells=[['Persistencia',p.durable?'DURABLE':p.ok?'MEMORIA':'SIN CONEXIÓN'],['Liquidación',settled+' cerrados · '+pending+' pendientes'],['Anomalías',Math.round(Number(a.anomalyRate||0)*1000)/10+'%'],['Perfil','SPORT + MARKET']];document.getElementById('mqOpsGrid').innerHTML=cells.map(x=>'<div style="padding:7px;border:1px solid rgba(90,180,200,.12);border-radius:7px"><small style="opacity:.55">'+esc(x[0])+'</small><b style="display:block;margin-top:3px">'+esc(x[1])+'</b></div>').join('');const errors=read('mq_model_errors_v1',[]).slice(0,6);document.getElementById('mqErrorRows').innerHTML=errors.length?errors.map(r=>'<div style="padding:7px;border:1px solid rgba(255,120,120,.15);border-radius:7px"><b>'+esc(r.selection)+'</b> · '+esc(r.market)+' · '+Math.round(Number(r.prob||0)*100)+'%<div style="opacity:.7;margin-top:3px">'+esc(r.cause)+' → '+esc(r.adjustment)+'</div></div>').join(''):'<div style="opacity:.55">Sin errores liquidados suficientes para diagnosticar.</div>'}

function boot(){dataQuality();enrichHistory();diagnoseErrors(read('mq_history',[]));pullState().finally(()=>{setTimeout(pushState,1500);setTimeout(autoSettle,2500)});mountOpsPanel();setInterval(()=>{dataQuality();renderOps()},15000);setInterval(pushState,60000);setInterval(autoSettle,30*60000);const mo=new MutationObserver(()=>mountOpsPanel());mo.observe(document.documentElement,{childList:true,subtree:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
