const FOOT='https://v3.football.api-sports.io';
const MAX_HISTORY=800;
const MAX_SETTLE_FIXTURES=6;
const HALF_LIFE_DAYS=60;

function cors(req,res){const origin=String(req.headers&&req.headers.origin||'');if(origin.endsWith('.vercel.app')||origin==='https://enderduque1758-png.github.io')res.setHeader('Access-Control-Allow-Origin',origin);res.setHeader('Vary','Origin');res.setHeader('Access-Control-Allow-Methods','POST,OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type,X-Odds-Api-Key');res.setHeader('Cache-Control','no-store')}
function send(req,res,status,data){cors(req,res);return res.status(status).json(data)}
function clamp(v,lo=.01,hi=.99){v=Number(v);return Number.isFinite(v)?Math.max(lo,Math.min(hi,v)):null}
function norm(v=''){return String(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()}
function histKey(r){return[r.fixture,r.market||'h2h',r.description||'',r.name||r.side||'',r.point==null?'':r.point].join('|')}
function footKey(){return String(process.env.API_FOOTBALL_KEY||'').trim()}
async function football(path){const key=footKey();if(!key)throw new Error('Falta API_FOOTBALL_KEY en Vercel');const r=await fetch(FOOT+path,{headers:{'x-apisports-key':key}}),text=await r.text();let data;try{data=JSON.parse(text)}catch{data={message:text||'Respuesta inválida de API-FOOTBALL'}}if(!r.ok)throw new Error(data.message||`API-FOOTBALL ${r.status}`);return Array.isArray(data.response)?data.response:[]}
function isFinal(f){return['FT','AET','PEN'].includes(String(f&&f.fixture&&f.fixture.status&&f.fixture.status.short||''))}
function overUnder(value,point,name){value=Number(value);point=Number(point);if(!Number.isFinite(value)||!Number.isFinite(point))return null;const n=String(name||'').toLowerCase();if(Math.abs(value-point)<1e-9)return{voided:true};if(/under|menos/.test(n))return{outcome:value<point?1:0};if(/over|mas|más/.test(n))return{outcome:value>point?1:0};return null}
function sideFromRow(r){const n=norm(r.name),home=norm(r.home_team),away=norm(r.away_team);if(r.side)return r.side;if(home&&n===home)return'home';if(away&&n===away)return'away';if(/draw|empate/.test(String(r.name||'').toLowerCase()))return'draw';return null}
function spreadSettle(r,home,away){const side=sideFromRow(r),point=Number(r.point);if(!side||side==='draw'||!Number.isFinite(point))return null;const mine=side==='home'?Number(home):Number(away),opp=side==='home'?Number(away):Number(home),v=mine+point-opp;if(Math.abs(v)<1e-9)return{voided:true};return{outcome:v>0?1:0}}
function teamValue(r,homeName,awayName,homeValue,awayValue){const d=norm(r.description),n=norm(r.name);if(d&&d===norm(homeName))return Number(homeValue);if(d&&d===norm(awayName))return Number(awayValue);if(n===norm(homeName))return Number(homeValue);if(n===norm(awayName))return Number(awayValue);return null}
function settleBase(r,f){const m=String(r.market||'h2h'),hg=Number(f.goals&&f.goals.home),ag=Number(f.goals&&f.goals.away),winner=hg>ag?'home':hg<ag?'away':'draw',n=String(r.name||'').toLowerCase();if(!Number.isFinite(hg)||!Number.isFinite(ag))return null;if(m==='h2h'){const side=sideFromRow(r);return side?{outcome:side===winner?1:0}:null}if(m==='double_chance'){const x=n.replace(/\s/g,'');return{outcome:(x==='1x'&&winner!=='away')||(x==='x2'&&winner!=='home')||(x==='12'&&winner!=='draw')?1:0}}if(m==='draw_no_bet'){if(winner==='draw')return{voided:true};const side=sideFromRow(r);return side?{outcome:side===winner?1:0}:null}if(m==='btts'){const yes=hg>0&&ag>0;return{outcome:/yes|si|sí/.test(n)?(yes?1:0):(yes?0:1)}}if(m==='totals'||m==='alternate_totals')return overUnder(hg+ag,r.point,r.name);if(m==='team_totals'||m==='alternate_team_totals'){const v=teamValue(r,r.home_team,r.away_team,hg,ag);return v==null?null:overUnder(v,r.point,r.name)}if(m==='spreads'||m==='alternate_spreads')return spreadSettle(r,hg,ag);if(m==='totals_h1'){const hh=Number(f.score&&f.score.halftime&&f.score.halftime.home),ha=Number(f.score&&f.score.halftime&&f.score.halftime.away);return Number.isFinite(hh)&&Number.isFinite(ha)?overUnder(hh+ha,r.point,r.name):null}return null}
function statNumber(rows,label){const key=norm(label);for(const t of rows||[]){for(const s of t.statistics||[]){if(norm(s.type)===key){const v=Number(String(s.value==null?'':s.value).replace('%',''));if(Number.isFinite(v))return v}}}return null}
function teamStatMap(rows){const out={};for(const t of rows||[]){const id=Number(t.team&&t.team.id);if(!id)continue;out[id]={corners:statNumber([t],'Corner Kicks'),yellow:statNumber([t],'Yellow Cards'),red:statNumber([t],'Red Cards'),shots:statNumber([t],'Total Shots'),shots_on_target:statNumber([t],'Shots on Goal')}}return out}
function playerMap(rows){const out={};for(const team of rows||[]){for(const row of team.players||[]){const p=row.player||{},s=(row.statistics||[])[0]||{},shots=s.shots||{},cards=s.cards||{};out[norm(p.name)]={name:p.name,shots:Number(shots.total||0),shots_on_target:Number(shots.on||0),cards:Number(cards.yellow||0)+Number(cards.red||0)}}}return out}
function settleSpecial(r,f,stats,players){const m=String(r.market||''),homeId=Number(f.teams&&f.teams.home&&f.teams.home.id),awayId=Number(f.teams&&f.teams.away&&f.teams.away.id),hs=stats&&stats[homeId]||{},as=stats&&stats[awayId]||{};if(m==='alternate_totals_corners')return overUnder(Number(hs.corners)+Number(as.corners),r.point,r.name);if(m==='alternate_team_totals_corners'){const v=teamValue(r,r.home_team,r.away_team,hs.corners,as.corners);return v==null?null:overUnder(v,r.point,r.name)}if(m==='corners_1x2'){if(!Number.isFinite(Number(hs.corners))||!Number.isFinite(Number(as.corners)))return null;const winner=Number(hs.corners)>Number(as.corners)?'home':Number(hs.corners)<Number(as.corners)?'away':'draw',side=sideFromRow(r);return side?{outcome:side===winner?1:0}:null}if(m==='alternate_spreads_corners')return spreadSettle(r,hs.corners,as.corners);if(m==='alternate_totals_cards'){const hc=Number(hs.yellow||0)+Number(hs.red||0),ac=Number(as.yellow||0)+Number(as.red||0);return overUnder(hc+ac,r.point,r.name)}if(m==='alternate_spreads_cards'){const hc=Number(hs.yellow||0)+Number(hs.red||0),ac=Number(as.yellow||0)+Number(as.red||0);return spreadSettle(r,hc,ac)}if(/^player_(shots|shots_on_target|to_receive_card)$/.test(m)){const p=players&&players[norm(r.description||r.player||'')];if(!p)return null;if(m==='player_shots')return overUnder(p.shots,r.point,r.name);if(m==='player_shots_on_target')return overUnder(p.shots_on_target,r.point,r.name);if(m==='player_to_receive_card'){const yes=p.cards>0,n=String(r.name||'').toLowerCase();if(/yes|si|sí|over/.test(n))return{outcome:yes?1:0};if(/no|under/.test(n))return{outcome:yes?0:1}}}return null}
function needsStats(m){return/corner|card/.test(String(m||''))}
function needsPlayers(m){return/^player_(shots|shots_on_target|to_receive_card)$/.test(String(m||''))}
async function settleHistory(rows){const due=[...new Set(rows.filter(r=>!r.settled&&new Date(r.kickoff).getTime()<Date.now()-3*3600000).map(r=>Number(r.fixture)).filter(Boolean))].slice(0,MAX_SETTLE_FIXTURES);for(const id of due){try{const f=(await football(`/fixtures?id=${id}`))[0];if(!f||!isFinal(f))continue;const group=rows.filter(r=>Number(r.fixture)===id&&!r.settled),wantStats=group.some(r=>needsStats(r.market)),wantPlayers=group.some(r=>needsPlayers(r.market));let stats={},players={};if(wantStats)stats=teamStatMap(await football(`/fixtures/statistics?fixture=${id}`).catch(()=>[]));if(wantPlayers)players=playerMap(await football(`/fixtures/players?fixture=${id}`).catch(()=>[]));for(const r of group){const s=settleBase(r,f)||settleSpecial(r,f,stats,players);if(!s)continue;r.settled=true;r.voided=!!s.voided;r.settled_at=new Date().toISOString();if(!s.voided)r.outcome=Number(s.outcome)}}catch{}}return rows}
function ageWeight(kickoff,at=Date.now()){const t=new Date(kickoff).getTime();if(!Number.isFinite(t))return.5;const days=Math.max(0,(at-t)/86400000);return Math.pow(.5,days/HALF_LIFE_DAYS)}
function effectiveN(weights){const s=weights.reduce((a,b)=>a+b,0),s2=weights.reduce((a,b)=>a+b*b,0);return s2>0?s*s/s2:0}
function weightedMean(rows,field,now){let sw=0,s=0,ws=[];for(const r of rows){const w=ageWeight(r.kickoff,now),v=Number(r[field]);if(!Number.isFinite(v))continue;sw+=w;s+=w*v;ws.push(w)}return{value:sw?s/sw:null,weight:sw,effective_n:effectiveN(ws)}}
function posteriorActual(rows,now){let wins=0,losses=0,weights=[];for(const r of rows){const w=ageWeight(r.kickoff,now),y=Number(r.outcome);if(!Number.isFinite(y))continue;weights.push(w);wins+=w*y;losses+=w*(1-y)}return{value:(wins+3)/(wins+losses+6),effective_n:effectiveN(weights)}}
function bins(sample,now=Date.now()){const ranges=[[.01,.35],[.35,.45],[.45,.55],[.55,.65],[.65,1.01]];return ranges.map(([lo,hi])=>{const s=sample.filter(r=>Number(r.prob)>=lo&&Number(r.prob)<hi),pred=weightedMean(s,'prob',now),act=posteriorActual(s,now),active=s.length>=10&&act.effective_n>=7&&pred.value!=null,strength=active?Math.min(.82,act.effective_n/(act.effective_n+18)):0,raw=active?act.value-pred.value:0,adjustment=active?Math.max(-.05,Math.min(.05,raw*strength)):0,uncertainty=active?Math.min(.25,1/Math.sqrt(Math.max(1,act.effective_n))):.25;return{lo,hi,samples:s.length,effective_samples:Number(act.effective_n.toFixed(1)),predicted:pred.value,actual:act.value,active,adjustment,uncertainty}})}
function metrics(rows){if(!rows.length)return{samples:0,brier:null,log_loss:null,hit_rate:null,estimated_hit_rate:null,ece:null,bets:0,roi:null,drawdown:null,clv_pp:null,clv_samples:0};const eps=1e-6;let brier=0,ll=0,hit=0,est=0;for(const x of rows){const p=clamp(x.p),y=Number(x.outcome);brier+=(p-y)**2;ll+=-(y*Math.log(Math.max(eps,p))+(1-y)*Math.log(Math.max(eps,1-p)));hit+=y;est+=p}const bs=brier/rows.length,log=ll/rows.length,bets=rows.filter(x=>x.bet);let eq=0,peak=0,dd=0;for(const x of bets){eq+=x.profit;peak=Math.max(peak,eq);dd=Math.max(dd,peak-eq)}const buckets=bins(rows.map(x=>({prob:x.p,outcome:x.outcome,kickoff:x.kickoff})));let ece=0;for(const b of buckets){if(!b.samples||b.predicted==null||b.actual==null)continue;ece+=b.samples/rows.length*Math.abs(b.actual-b.predicted)}return{samples:rows.length,brier:bs,log_loss:log,hit_rate:hit/rows.length,estimated_hit_rate:est/rows.length,ece,bets:bets.length,roi:bets.length?bets.reduce((s,x)=>s+x.profit,0)/bets.length:null,drawdown:bets.length?dd:null,clv_pp:null,clv_samples:0}}
function summarizeByMarket(rows){const out={};for(const m of [...new Set(rows.map(x=>String(x.market||'h2h')))])out[m]=metrics(rows.filter(x=>String(x.market||'h2h')===m));return out}
function priorAdjustment(prior,prob,now){const lo=prob<.35?.01:prob<.45?.35:prob<.55?.45:prob<.65?.55:.65,hi=prob<.35?.35:prob<.45?.45:prob<.55?.55:prob<.65?.65:1.01,near=prior.filter(x=>Number(x.prob)>=lo&&Number(x.prob)<hi).slice(-120);if(near.length<10)return{adjustment:0,samples:near.length,effective:0};const pred=weightedMean(near,'prob',now),act=posteriorActual(near,now),strength=Math.min(.8,act.effective_n/(act.effective_n+18)),adj=Math.max(-.05,Math.min(.05,(act.value-pred.value)*strength));return{adjustment:adj,samples:near.length,effective:act.effective_n}}
function marketDrift(rows){const now=Date.now(),recent=rows.filter(x=>now-new Date(x.kickoff).getTime()<=30*86400000),older=rows.filter(x=>{const d=now-new Date(x.kickoff).getTime();return d>30*86400000&&d<=120*86400000});if(recent.length<8||older.length<12)return{active:false,score:0,recent_samples:recent.length,baseline_samples:older.length};const a=metrics(recent.map(r=>({p:Number(r.prob),outcome:Number(r.outcome),kickoff:r.kickoff,bet:false,profit:0}))),b=metrics(older.map(r=>({p:Number(r.prob),outcome:Number(r.outcome),kickoff:r.kickoff,bet:false,profit:0}))),score=Math.abs(Number(a.hit_rate)-Number(b.hit_rate))+Math.abs(Number(a.brier)-Number(b.brier));return{active:score>=.12,score,recent_samples:recent.length,baseline_samples:older.length}}
function reliabilityScore(summary,drift){const n=Number(summary.samples||0),b=summary.brier==null?.28:Number(summary.brier),ece=summary.ece==null?.12:Number(summary.ece);let score=Math.min(1,n/60)*.35+Math.max(0,1-b/.30)*.35+Math.max(0,1-ece/.15)*.30;if(drift&&drift.active)score*=.72;return Math.max(0,Math.min(1,score))}
function calibrate(rows){const settled=rows.filter(r=>r.settled&&!r.voided&&Number.isFinite(Number(r.outcome))&&Number.isFinite(Number(r.prob))).sort((a,b)=>new Date(a.kickoff)-new Date(b.kickoff)),markets=[...new Set(settled.map(r=>String(r.market||'h2h')))],market_bins={},wf=[],market_quality={};for(const m of markets){const part=settled.filter(r=>String(r.market||'h2h')===m).slice(-240);market_bins[m]=bins(part);const drift=marketDrift(part),summary=metrics(part.map(r=>({p:Number(r.prob),outcome:Number(r.outcome),kickoff:r.kickoff,bet:false,profit:0})));market_quality[m]={...drift,reliability:reliabilityScore(summary,drift),brier:summary.brier,ece:summary.ece,samples:summary.samples}}
for(let i=0;i<settled.length;i++){const r=settled[i],market=String(r.market||'h2h'),prior=settled.slice(0,i).filter(p=>String(p.market||'h2h')===market),base=clamp(r.prob),hist=priorAdjustment(prior,base,new Date(r.kickoff).getTime()),marketProb=clamp(r.market_prob),histStrength=Math.min(.75,hist.effective/(hist.effective+20)),marketWeight=marketProb==null?0:Math.max(.08,Math.min(.32,.30-histStrength*.20)),p=clamp(base+hist.adjustment);const blended=marketProb==null?p:clamp(p*(1-marketWeight)+marketProb*marketWeight),price=Number(r.price||0),bet=price>1&&blended*price>1.015,profit=bet?(Number(r.outcome)===1?price-1:-1):0;wf.push({market,kickoff:r.kickoff,p:blended,raw_p:base,market_p:marketProb,outcome:Number(r.outcome),bet,profit,history_samples:hist.samples})}
const by_market=summarizeByMarket(wf),walk_forward={...metrics(wf),by_market},performance_windows={};for(const days of[7,30,90]){const cutoff=Date.now()-days*86400000,part=wf.filter(x=>new Date(x.kickoff).getTime()>=cutoff);performance_windows[String(days)]={...metrics(part),by_market:summarizeByMarket(part)}}return{version:'adaptive-v2',samples:settled.length,market_bins,market_quality,walk_forward,performance_windows,history_learning_active:Object.values(market_bins).some(x=>x.some(b=>b.active)),pending:rows.filter(r=>!r.settled).length,settled:settled.length,data_quality:{supported_settlements:settled.length,unsupported_pending:rows.filter(r=>!r.settled&&new Date(r.kickoff).getTime()<Date.now()-6*3600000).length,half_life_days:HALF_LIFE_DAYS,max_history:MAX_HISTORY}}}

export default async function handler(req,res){if(req.method==='OPTIONS'){cors(req,res);return res.status(204).end()}if(req.method!=='POST')return send(req,res,405,{error:'Método no permitido'});try{const body=req.body||{},map=new Map((Array.isArray(body.history)?body.history:[]).slice(-MAX_HISTORY).map(r=>[histKey(r),r]));for(const r of(Array.isArray(body.predictions)?body.predictions:[]).slice(0,120)){const prob=clamp(r.prob),marketProb=clamp(r.market_prob);if(prob==null)continue;const clean={...r,fixture:Number(r.fixture),market:String(r.market||'h2h'),prob,market_prob:marketProb,price:Number(r.price)||undefined,settled:false,created_at:r.created_at||new Date().toISOString()};if(!map.has(histKey(clean)))map.set(histKey(clean),clean)}let history=[...map.values()].sort((a,b)=>new Date(a.kickoff)-new Date(b.kickoff)).slice(-MAX_HISTORY);if(footKey())history=await settleHistory(history);const calibration=calibrate(history);return send(req,res,200,{history,calibration,engine:{version:'adaptive-v2',features:['recency_weighting','bayesian_shrinkage','walk_forward_no_leakage','market_blending','drift_detection','uncertainty','special_market_settlement'],api_football:!!footKey()}})}catch(err){return send(req,res,500,{error:err instanceof Error?err.message:String(err)})}}
