import {getJson,setJson,persistenceInfo} from '../server/store.js';
import {settleCore,norm,scorePair} from '../server/settlement.js';

const ODDS='https://api.the-odds-api.com/v4';
const FOOT='https://v3.football.api-sports.io';
function send(res,status,data){res.setHeader('Cache-Control','no-store');res.setHeader('Content-Type','application/json; charset=utf-8');return res.status(status).json(data)}
function oddsKey(){const k=String(process.env.THE_ODDS_API_KEY||'').trim();if(!k)throw new Error('Falta THE_ODDS_API_KEY en Vercel');return k}
function footKey(){return String(process.env.API_FOOTBALL_KEY||'').trim()}
async function jsonFetch(url,opt={}){const r=await fetch(url,opt),t=await r.text();let d;try{d=JSON.parse(t)}catch{d={message:t}}if(!r.ok)throw new Error(d.message||d.error||`HTTP ${r.status}`);return d}
async function scores(sport,days=3){const u=`${ODDS}/sports/${encodeURIComponent(sport)}/scores/?daysFrom=${Math.max(1,Math.min(3,days))}&apiKey=${encodeURIComponent(oddsKey())}`;const d=await jsonFetch(u);return Array.isArray(d)?d:[]}
async function football(path){const k=footKey();if(!k)return null;const d=await jsonFetch(FOOT+path,{headers:{'x-apisports-key':k}});return Array.isArray(d.response)?d.response:[]}
function statValue(rows,name){const r=(rows||[]).find(x=>norm(x.type)===norm(name));const v=r&&r.value;if(typeof v==='string'&&v.endsWith('%'))return Number(v.slice(0,-1));return Number(v)}
async function soccerDetail(p,event){if(!String(p.sport_key||'').startsWith('soccer_')||!footKey())return{};const fixture=Number(p.fixture||p.football_fixture||0);if(!fixture)return{};const rows=await football(`/fixtures?id=${fixture}`);const f=rows&&rows[0];if(!f)return{};const detail={};const fh=Number(f.goals&&f.goals.home),fa=Number(f.goals&&f.goals.away);if(Number.isFinite(fh)&&Number.isFinite(fa))detail.final={home:fh,away:fa};const hh=Number(f.score&&f.score.halftime&&f.score.halftime.home),ha=Number(f.score&&f.score.halftime&&f.score.halftime.away);if(Number.isFinite(hh)&&Number.isFinite(ha))detail.halftime={home:hh,away:ha};
 try{const s=await football(`/fixtures/statistics?fixture=${fixture}`);if(Array.isArray(s)&&s.length>=2){const home=s.find(x=>Number(x.team&&x.team.id)===Number(f.teams&&f.teams.home&&f.teams.home.id))||s[0],away=s.find(x=>Number(x.team&&x.team.id)===Number(f.teams&&f.teams.away&&f.teams.away.id))||s[1];detail.corners={home:statValue(home.statistics,'Corner Kicks'),away:statValue(away.statistics,'Corner Kicks')};detail.cards={home:(statValue(home.statistics,'Yellow Cards')||0)+(statValue(home.statistics,'Red Cards')||0),away:(statValue(away.statistics,'Yellow Cards')||0)+(statValue(away.statistics,'Red Cards')||0)}}}catch{}
 try{const teams=await football(`/fixtures/players?fixture=${fixture}`);const players=[];for(const team of teams||[])for(const row of team.players||[]){const st=(row.statistics||[])[0]||{},shots=st.shots||{},goals=st.goals||{},cards=st.cards||{};players.push({name:row.player&&row.player.name,shots:Number(shots.total||0),shots_on_target:Number(shots.on||0),goals:Number(goals.total||0),yellow:Number(cards.yellow||0),red:Number(cards.red||0)})}detail.players=players}catch{}
 return detail}
function eventForPick(p,map){if(p.event_id&&map.has(String(p.event_id)))return map.get(String(p.event_id));for(const e of map.values()){if(String(e.sport_key||'')!==String(p.sport_key||''))continue;if(norm(e.home_team)===norm(p.home_team)&&norm(e.away_team)===norm(p.away_team))return e}return null}

export default async function handler(req,res){try{if(req.method!=='POST')return send(res,405,{error:'Método no permitido'});const body=typeof req.body==='string'?JSON.parse(req.body||'{}'):(req.body||{}),scope=String(body.scope||'default').replace(/[^a-z0-9:_-]/gi,'').slice(0,80)||'default',incoming=Array.isArray(body.picks)?body.picks:await getJson('mq:history:'+scope,[]),groups={};incoming.filter(p=>p&&!p.settled&&p.sport_key).forEach(p=>(groups[p.sport_key]||(groups[p.sport_key]=[])).push(p));const eventMap=new Map();for(const sport of Object.keys(groups)){const rows=await scores(sport,3);rows.forEach(e=>eventMap.set(String(e.id),e))}const out=[];for(const p of incoming){if(!p||p.settled||!p.sport_key){out.push(p);continue}const event=eventForPick(p,eventMap);if(!event){out.push(p);continue}const detail=await soccerDetail(p,event).catch(()=>({}));out.push(settleCore(p,event,detail))}await setJson('mq:history:'+scope,out);const changed=out.filter((p,i)=>p&&p.settled&&!incoming[i]?.settled).length,unsupported=out.filter((p,i)=>!incoming[i]?.settled&&p&&p.status==='unsupported_data').length;return send(res,200,{ok:true,settled:changed,unsupported,history:out,persistence:persistenceInfo()})}catch(e){return send(res,500,{error:e.message||String(e),persistence:persistenceInfo()})}}
