import {getJson,setJson,persistenceInfo} from '../server/store.js';

const ODDS='https://api.the-odds-api.com/v4';
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,Number(v)||0));
function send(res,status,data){res.setHeader('Cache-Control','no-store');return res.status(status).json(data)}
function oddsKey(){const k=String(process.env.THE_ODDS_API_KEY||'').trim();if(!k)throw new Error('Falta THE_ODDS_API_KEY en Vercel');return k}
function norm(v=''){return String(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()}
async function scores(sport,days=3){const u=`${ODDS}/sports/${encodeURIComponent(sport)}/scores/?daysFrom=${Math.max(1,Math.min(3,days))}&apiKey=${encodeURIComponent(oddsKey())}`;const r=await fetch(u);const text=await r.text();let d;try{d=JSON.parse(text)}catch{d={message:text}}if(!r.ok)throw new Error(d.message||`Scores ${r.status}`);return Array.isArray(d)?d:[]}
function scorePair(event){const scores=Array.isArray(event&&event.scores)?event.scores:[];if(scores.length<2)return null;const home=scores.find(x=>norm(x.name)===norm(event.home_team))||scores[0],away=scores.find(x=>norm(x.name)===norm(event.away_team))||scores[1],hg=Number(home&&home.score),ag=Number(away&&away.score);return Number.isFinite(hg)&&Number.isFinite(ag)?{hg,ag}:null}
function settlePick(p,event){const s=scorePair(event);if(!event||!event.completed||!s)return{...p,settled:false,status:'pending'};const m=String(p.market||''),name=String(p.name||p.selection||''),n=norm(name),point=p.point==null?null:Number(p.point);let outcome=null,voided=false;
 if(m==='h2h'||m==='draw_no_bet'){const home=norm(p.home_team||event.home_team),away=norm(p.away_team||event.away_team);if(s.hg===s.ag){if(m==='draw_no_bet')voided=true;else outcome=/draw|empate/.test(n)?1:0}else if(s.hg>s.ag)outcome=n.includes(home)?1:0;else outcome=n.includes(away)?1:0}
 else if(m==='totals'||m==='alternate_totals'||m==='totals_h1'){if(!Number.isFinite(point))return{...p,settled:false,status:'unsupported'};const total=s.hg+s.ag;if(total===point)voided=true;else if(/over|mas|más/.test(n))outcome=total>point?1:0;else if(/under|menos/.test(n))outcome=total<point?1:0}
 else if(m==='spreads'||m==='alternate_spreads'){if(!Number.isFinite(point))return{...p,settled:false,status:'unsupported'};const isHome=n.includes(norm(p.home_team||event.home_team)),isAway=n.includes(norm(p.away_team||event.away_team));const margin=isHome?s.hg-s.ag+point:isAway?s.ag-s.hg+point:null;if(margin==null)return{...p,settled:false,status:'unsupported'};if(margin===0)voided=true;else outcome=margin>0?1:0}
 else if(m==='btts'){const yes=s.hg>0&&s.ag>0;outcome=/yes|si|sí/.test(n)?(yes?1:0):/no/.test(n)?(yes?0:1):null}
 else return{...p,settled:false,status:'unsupported'};
 const price=Number(p.price),prob=clamp(p.prob),close=Number(p.close_price||p.closing_price),roi=voided?0:(outcome===1&&price>1?price-1:-1),brier=voided?null:Math.pow(prob-Number(outcome||0),2),clv=Number.isFinite(close)&&close>1&&price>1?((price/close)-1)*100:null;
 return{...p,settled:true,voided,outcome:voided?null:outcome,status:voided?'void':outcome===1?'won':'lost',final_score:`${s.hg}-${s.ag}`,roi,brier,closing_price:Number.isFinite(close)?close:null,clv_pp:clv,settled_at:new Date().toISOString()}}

export default async function handler(req,res){try{if(req.method!=='POST')return send(res,405,{error:'Método no permitido'});const body=typeof req.body==='string'?JSON.parse(req.body||'{}'):(req.body||{}),scope=String(body.scope||'default').replace(/[^a-z0-9:_-]/gi,'').slice(0,80)||'default',incoming=Array.isArray(body.picks)?body.picks:await getJson('mq:history:'+scope,[]),groups={};incoming.filter(p=>p&&!p.settled&&p.sport_key).forEach(p=>(groups[p.sport_key]||(groups[p.sport_key]=[])).push(p));const scoreMap=new Map();for(const sport of Object.keys(groups)){const rows=await scores(sport,3);rows.forEach(e=>scoreMap.set(String(e.id),e))}const out=incoming.map(p=>p&&p.event_id&&scoreMap.has(String(p.event_id))?settlePick(p,scoreMap.get(String(p.event_id))):p);await setJson('mq:history:'+scope,out);const changed=out.filter((p,i)=>p&&p.settled&&!incoming[i]?.settled).length;return send(res,200,{ok:true,settled:changed,history:out,persistence:persistenceInfo()})}catch(e){return send(res,500,{error:e.message||String(e),persistence:persistenceInfo()})}}
